/* tslint:disable */
/* eslint-disable */
/**
 * Contact System API
 * This is the spec for the Constact system API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dirk@arends.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ContactData,
    ContactDataFromJSON,
    ContactDataFromJSONTyped,
    ContactDataToJSON,
} from './';

/**
 * A list of contacts
 * @export
 * @interface Contacts
 */
export interface Contacts {
    /**
     * Array containg the list
     * @type {Array<ContactData>}
     * @memberof Contacts
     */
    contacts: Array<ContactData>;
}

export function ContactsFromJSON(json: any): Contacts {
    return ContactsFromJSONTyped(json, false);
}

export function ContactsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Contacts {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contacts': ((json['contacts'] as Array<any>).map(ContactDataFromJSON)),
    };
}

export function ContactsToJSON(value?: Contacts | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contacts': ((value.contacts as Array<any>).map(ContactDataToJSON)),
    };
}


