/* tslint:disable */
/* eslint-disable */
/**
 * Contact System API
 * This is the spec for the Constact system API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dirk@arends.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListType
 */
export interface ListType {
    /**
     * 
     * @type {string}
     * @memberof ListType
     */
    id?: string;
}

export function ListTypeFromJSON(json: any): ListType {
    return ListTypeFromJSONTyped(json, false);
}

export function ListTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function ListTypeToJSON(value?: ListType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


