/* tslint:disable */
/* eslint-disable */
/**
 * Contact System API
 * This is the spec for the Constact system API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dirk@arends.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoleInput
 */
export interface RoleInput {
    /**
     * 
     * @type {string}
     * @memberof RoleInput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RoleInput
     */
    externalId?: string;
    /**
     * 
     * @type {number}
     * @memberof RoleInput
     */
    sectionId: number;
}

export function RoleInputFromJSON(json: any): RoleInput {
    return RoleInputFromJSONTyped(json, false);
}

export function RoleInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'externalId': !exists(json, 'externalId') ? undefined : json['externalId'],
        'sectionId': json['sectionId'],
    };
}

export function RoleInputToJSON(value?: RoleInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'externalId': value.externalId,
        'sectionId': value.sectionId,
    };
}


