=begin comment

Contact System API

This is the spec for the Constact system API

The version of the OpenAPI document: 1.0.0
Contact: dirk@arends.com.au
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::RolesApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# create_role
#
# Create role
# 
# @param RoleInput $role_input  (optional)
{
    my $params = {
    'role_input' => {
        data_type => 'RoleInput',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'create_role' } = { 
        summary => 'Create role',
        params => $params,
        returns => 'RoleResponse',
        };
}
# @return RoleResponse
#
sub create_role {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/roles';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'role_input'}) {
        $_body_data = $args{'role_input'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(contact_auth jwt_auth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('RoleResponse', $response);
    return $_response_object;
}

#
# delete_role_by_id
#
# Delete role
# 
# @param int $role_id  (required)
{
    my $params = {
    'role_id' => {
        data_type => 'int',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'delete_role_by_id' } = { 
        summary => 'Delete role',
        params => $params,
        returns => 'ApiResponse',
        };
}
# @return ApiResponse
#
sub delete_role_by_id {
    my ($self, %args) = @_;

    # verify the required parameter 'role_id' is set
    unless (exists $args{'role_id'}) {
      croak("Missing the required parameter 'role_id' when calling delete_role_by_id");
    }

    # parse inputs
    my $_resource_path = '/roles/{roleId}';

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'role_id'}) {
        my $_base_variable = "{" . "roleId" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'role_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(contact_auth jwt_auth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ApiResponse', $response);
    return $_response_object;
}

#
# get_list_rules_by_role_id
#
# List Rules by Role ID
# 
# @param int $role_id  (required)
# @param string $query  (optional)
# @param string $sort  (optional)
# @param int $page_size  (optional)
# @param int $page  (optional)
{
    my $params = {
    'role_id' => {
        data_type => 'int',
        description => '',
        required => '1',
    },
    'query' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'sort' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'page_size' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'page' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_list_rules_by_role_id' } = { 
        summary => 'List Rules by Role ID',
        params => $params,
        returns => 'ListRules',
        };
}
# @return ListRules
#
sub get_list_rules_by_role_id {
    my ($self, %args) = @_;

    # verify the required parameter 'role_id' is set
    unless (exists $args{'role_id'}) {
      croak("Missing the required parameter 'role_id' when calling get_list_rules_by_role_id");
    }

    # parse inputs
    my $_resource_path = '/roles/{roleId}/list-rules';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'query'}) {
        $query_params->{'query'} = $self->{api_client}->to_query_value($args{'query'});
    }

    # query params
    if ( exists $args{'sort'}) {
        $query_params->{'sort'} = $self->{api_client}->to_query_value($args{'sort'});
    }

    # query params
    if ( exists $args{'page_size'}) {
        $query_params->{'pageSize'} = $self->{api_client}->to_query_value($args{'page_size'});
    }

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # path params
    if ( exists $args{'role_id'}) {
        my $_base_variable = "{" . "roleId" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'role_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(contact_auth jwt_auth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ListRules', $response);
    return $_response_object;
}

#
# get_members_by_role_id
#
# List members by role
# 
# @param int $role_id  (required)
# @param string $query  (optional)
# @param string $sort  (optional)
# @param int $page_size  (optional)
# @param int $page  (optional)
{
    my $params = {
    'role_id' => {
        data_type => 'int',
        description => '',
        required => '1',
    },
    'query' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'sort' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'page_size' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'page' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_members_by_role_id' } = { 
        summary => 'List members by role',
        params => $params,
        returns => 'Members',
        };
}
# @return Members
#
sub get_members_by_role_id {
    my ($self, %args) = @_;

    # verify the required parameter 'role_id' is set
    unless (exists $args{'role_id'}) {
      croak("Missing the required parameter 'role_id' when calling get_members_by_role_id");
    }

    # parse inputs
    my $_resource_path = '/roles/{roleId}/members';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'query'}) {
        $query_params->{'query'} = $self->{api_client}->to_query_value($args{'query'});
    }

    # query params
    if ( exists $args{'sort'}) {
        $query_params->{'sort'} = $self->{api_client}->to_query_value($args{'sort'});
    }

    # query params
    if ( exists $args{'page_size'}) {
        $query_params->{'pageSize'} = $self->{api_client}->to_query_value($args{'page_size'});
    }

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # path params
    if ( exists $args{'role_id'}) {
        my $_base_variable = "{" . "roleId" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'role_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(contact_auth jwt_auth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Members', $response);
    return $_response_object;
}

#
# get_role_by_id
#
# Get Role
# 
# @param int $role_id  (required)
{
    my $params = {
    'role_id' => {
        data_type => 'int',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_role_by_id' } = { 
        summary => 'Get Role',
        params => $params,
        returns => 'RoleResponse',
        };
}
# @return RoleResponse
#
sub get_role_by_id {
    my ($self, %args) = @_;

    # verify the required parameter 'role_id' is set
    unless (exists $args{'role_id'}) {
      croak("Missing the required parameter 'role_id' when calling get_role_by_id");
    }

    # parse inputs
    my $_resource_path = '/roles/{roleId}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'role_id'}) {
        my $_base_variable = "{" . "roleId" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'role_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(contact_auth jwt_auth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('RoleResponse', $response);
    return $_response_object;
}

#
# get_roles
#
# Get roles
# 
# @param string $query  (optional)
# @param string $sort  (optional)
# @param int $page_size  (optional)
# @param int $page  (optional)
{
    my $params = {
    'query' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'sort' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'page_size' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'page' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_roles' } = { 
        summary => 'Get roles',
        params => $params,
        returns => 'Roles',
        };
}
# @return Roles
#
sub get_roles {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/roles';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'query'}) {
        $query_params->{'query'} = $self->{api_client}->to_query_value($args{'query'});
    }

    # query params
    if ( exists $args{'sort'}) {
        $query_params->{'sort'} = $self->{api_client}->to_query_value($args{'sort'});
    }

    # query params
    if ( exists $args{'page_size'}) {
        $query_params->{'pageSize'} = $self->{api_client}->to_query_value($args{'page_size'});
    }

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(contact_auth jwt_auth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Roles', $response);
    return $_response_object;
}

#
# update_role_by_id
#
# Update role
# 
# @param int $role_id  (required)
# @param RoleInput $role_input  (optional)
{
    my $params = {
    'role_id' => {
        data_type => 'int',
        description => '',
        required => '1',
    },
    'role_input' => {
        data_type => 'RoleInput',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'update_role_by_id' } = { 
        summary => 'Update role',
        params => $params,
        returns => 'RoleResponse',
        };
}
# @return RoleResponse
#
sub update_role_by_id {
    my ($self, %args) = @_;

    # verify the required parameter 'role_id' is set
    unless (exists $args{'role_id'}) {
      croak("Missing the required parameter 'role_id' when calling update_role_by_id");
    }

    # parse inputs
    my $_resource_path = '/roles/{roleId}';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'role_id'}) {
        my $_base_variable = "{" . "roleId" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'role_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'role_input'}) {
        $_body_data = $args{'role_input'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(contact_auth jwt_auth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('RoleResponse', $response);
    return $_response_object;
}

1;
