<?php
/**
 * MemberSuggestion
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Contact System API
 *
 * This is the spec for the Constact system API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dirk@arends.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the MemberSuggestion model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class MemberSuggestion 
{
        /**
     * Array containg the list
     *
     * @var string[]
     * @SerializedName("memberIds")
     * @Assert\NotNull()
     * @Assert\All({
     *   @Assert\Type("string")
     * })
     * @Type("array<string>")
     */
    protected $memberIds;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->memberIds = isset($data['memberIds']) ? $data['memberIds'] : null;
    }

    /**
     * Gets memberIds.
     *
     * @return string[]
     */
    public function getMemberIds(): array
    {
        return $this->memberIds;
    }

    /**
     * Sets memberIds.
     *
     * @param string[] $memberIds  Array containg the list
     *
     * @return $this
     */
    public function setMemberIds(array $memberIds): array
    {
        $this->memberIds = $memberIds;

        return $this;
    }
}


