<?php
/**
 * GroupsApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Server
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Contact System API
 *
 * This is the spec for the Constact system API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dirk@arends.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use OpenAPI\Server\Model\ApiResponse;
use OpenAPI\Server\Model\GroupData;
use OpenAPI\Server\Model\GroupInput;
use OpenAPI\Server\Model\MemberData;
use OpenAPI\Server\Model\SectionData;

/**
 * GroupsApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  OpenAPI\Server\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface GroupsApiInterface
{

    /**
     * Sets authentication method contact_auth
     *
     * @param string $value Value of the contact_auth authentication method.
     *
     * @return void
     */
    public function setcontact_auth($value);

    /**
     * Operation addGroupLocalMarkerById
     *
     * @param  string $groupId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\ApiResponse
     *
     */
    public function addGroupLocalMarkerById($groupId, &$responseCode, array &$responseHeaders);

    /**
     * Operation createGroup
     *
     * @param  OpenAPI\Server\Model\GroupInput $groupInput   (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\GroupData
     *
     */
    public function createGroup(GroupInput $groupInput = null, &$responseCode, array &$responseHeaders);

    /**
     * Operation deleteGroupLocalMarkerById
     *
     * @param  string $groupId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\ApiResponse
     *
     */
    public function deleteGroupLocalMarkerById($groupId, &$responseCode, array &$responseHeaders);

    /**
     * Operation getGroupMembersById
     *
     * Your GET endpoint
     *
     * @param  string $groupId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\MemberData[]
     *
     */
    public function getGroupMembersById($groupId, &$responseCode, array &$responseHeaders);

    /**
     * Operation getGroupSectionsById
     *
     * Your GET endpoint
     *
     * @param  string $groupId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\SectionData[]
     *
     */
    public function getGroupSectionsById($groupId, &$responseCode, array &$responseHeaders);

    /**
     * Operation getGroups
     *
     * Your GET endpoint
     *
     * @param  string $sort   (optional)
     * @param  int $pageSize   (optional)
     * @param  int $page   (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\GroupData[]
     *
     */
    public function getGroups($sort = null, $pageSize = null, $page = null, &$responseCode, array &$responseHeaders);
}
