<?php
/**
 * MembersApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Server
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Contact System API
 *
 * This is the spec for the Constact system API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dirk@arends.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use OpenAPI\Server\Model\ApiResponse;
use OpenAPI\Server\Model\Group;
use OpenAPI\Server\Model\InlineObject;
use OpenAPI\Server\Model\InlineObject1;
use OpenAPI\Server\Model\Member;
use OpenAPI\Server\Model\MemberSuggetion;
use OpenAPI\Server\Model\Members;

/**
 * MembersApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  OpenAPI\Server\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface MembersApiInterface
{

    /**
     * Sets authentication method contact_auth
     *
     * @param string $value Value of the contact_auth authentication method.
     *
     * @return void
     */
    public function setcontact_auth($value);

    /**
     * Operation addMemberLocalMarkerById
     *
     * Add local marker
     *
     * @param  string $memberId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\ApiResponse
     *
     */
    public function addMemberLocalMarkerById($memberId, &$responseCode, array &$responseHeaders);

    /**
     * Operation createMember
     *
     * Create a member
     *
     * @param  OpenAPI\Server\Model\Member $member   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Member
     *
     */
    public function createMember(Member $member, &$responseCode, array &$responseHeaders);

    /**
     * Operation deleteMemberById
     *
     * Delete member
     *
     * @param  string $memberId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Member
     *
     */
    public function deleteMemberById($memberId, &$responseCode, array &$responseHeaders);

    /**
     * Operation getMemberById
     *
     * Get member
     *
     * @param  string $memberId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Member
     *
     */
    public function getMemberById($memberId, &$responseCode, array &$responseHeaders);

    /**
     * Operation getMemberLocalMarkerSuggestionsById
     *
     * Get member suggestions
     *
     * @param  string $memberId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\MemberSuggetion[]
     *
     */
    public function getMemberLocalMarkerSuggestionsById($memberId, &$responseCode, array &$responseHeaders);

    /**
     * Operation getMembers
     *
     * List all members
     *
     * @param  string $sort   (optional)
     * @param  int $pageSize   (optional)
     * @param  int $page   (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Members
     *
     */
    public function getMembers($sort = null, $pageSize = null, $page = null, &$responseCode, array &$responseHeaders);

    /**
     * Operation mergeMember
     *
     * Merge member
     *
     * @param  string $memberId   (required)
     * @param  string $mergeMemberId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\ApiResponse
     *
     */
    public function mergeMember($memberId, $mergeMemberId, &$responseCode, array &$responseHeaders);

    /**
     * Operation removeMemberLocalMarkerById
     *
     * Remove local marker
     *
     * @param  string $memberId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array
     *
     */
    public function removeMemberLocalMarkerById($memberId, &$responseCode, array &$responseHeaders);

    /**
     * Operation removeMemberSectionById
     *
     * @param  string $memberId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\ApiResponse
     *
     */
    public function removeMemberSectionById($memberId, &$responseCode, array &$responseHeaders);

    /**
     * Operation setMemberGroupById
     *
     * @param  string $memberId   (required)
     * @param  OpenAPI\Server\Model\InlineObject1 $inlineObject1   (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Group
     *
     */
    public function setMemberGroupById($memberId, InlineObject1 $inlineObject1 = null, &$responseCode, array &$responseHeaders);

    /**
     * Operation setMemberSectionById
     *
     * @param  string $memberId   (required)
     * @param  OpenAPI\Server\Model\InlineObject $inlineObject   (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\ApiResponse
     *
     */
    public function setMemberSectionById($memberId, InlineObject $inlineObject = null, &$responseCode, array &$responseHeaders);

    /**
     * Operation updateMemberById
     *
     * Update member
     *
     * @param  string $memberId   (required)
     * @param  OpenAPI\Server\Model\Member $member   (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Member
     *
     */
    public function updateMemberById($memberId, Member $member = null, &$responseCode, array &$responseHeaders);
}
