<?php
/**
 * ParentsApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Server
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Contact System API
 *
 * This is the spec for the Constact system API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dirk@arends.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use OpenAPI\Server\Model\ApiResponse;
use OpenAPI\Server\Model\Group;
use OpenAPI\Server\Model\MemberParent;

/**
 * ParentsApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  OpenAPI\Server\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface ParentsApiInterface
{

    /**
     * Sets authentication method contact_auth
     *
     * @param string $value Value of the contact_auth authentication method.
     *
     * @return void
     */
    public function setcontact_auth($value);

    /**
     * Operation createParent
     *
     * @param  OpenAPI\Server\Model\MemberParent $memberParent   (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\MemberParent
     *
     */
    public function createParent(MemberParent $memberParent = null, &$responseCode, array &$responseHeaders);

    /**
     * Operation deleteGroupById
     *
     * @param  string $groupId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\ApiResponse
     *
     */
    public function deleteGroupById($groupId, &$responseCode, array &$responseHeaders);

    /**
     * Operation deleteParentById
     *
     * @param  string $parentId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\ApiResponse
     *
     */
    public function deleteParentById($parentId, &$responseCode, array &$responseHeaders);

    /**
     * Operation getGroupById
     *
     * Your GET endpoint
     *
     * @param  string $groupId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Group
     *
     */
    public function getGroupById($groupId, &$responseCode, array &$responseHeaders);

    /**
     * Operation getParentById
     *
     * Your GET endpoint
     *
     * @param  string $parentId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\MemberParent
     *
     */
    public function getParentById($parentId, &$responseCode, array &$responseHeaders);

    /**
     * Operation getParentMembersById
     *
     * Your GET endpoint
     *
     * @param  string $parentId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return string[]
     *
     */
    public function getParentMembersById($parentId, &$responseCode, array &$responseHeaders);

    /**
     * Operation getParents
     *
     * Your GET endpoint
     *
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\MemberParent[]
     *
     */
    public function getParents(&$responseCode, array &$responseHeaders);

    /**
     * Operation updateGroupById
     *
     * @param  string $groupId   (required)
     * @param  OpenAPI\Server\Model\Group $group   (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Group
     *
     */
    public function updateGroupById($groupId, Group $group = null, &$responseCode, array &$responseHeaders);

    /**
     * Operation updateParentById
     *
     * @param  string $parentId   (required)
     * @param  OpenAPI\Server\Model\MemberParent $memberParent   (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\MemberParent
     *
     */
    public function updateParentById($parentId, MemberParent $memberParent = null, &$responseCode, array &$responseHeaders);
}
