<?php
/**
 * RolesApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Server
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Contact System API
 *
 * This is the spec for the Constact system API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dirk@arends.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use OpenAPI\Server\Model\ApiResponse;
use OpenAPI\Server\Model\Role;

/**
 * RolesApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  OpenAPI\Server\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface RolesApiInterface
{

    /**
     * Sets authentication method contact_auth
     *
     * @param string $value Value of the contact_auth authentication method.
     *
     * @return void
     */
    public function setcontact_auth($value);

    /**
     * Operation deleteRolesCustomCustomRoleId
     *
     * @param  string $customRoleId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\ApiResponse
     *
     */
    public function deleteRolesCustomCustomRoleId($customRoleId, &$responseCode, array &$responseHeaders);

    /**
     * Operation getRolesCustom
     *
     * Your GET endpoint
     *
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Role[]
     *
     */
    public function getRolesCustom(&$responseCode, array &$responseHeaders);

    /**
     * Operation getRolesCustomCustomRoleId
     *
     * Your GET endpoint
     *
     * @param  string $customRoleId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Role
     *
     */
    public function getRolesCustomCustomRoleId($customRoleId, &$responseCode, array &$responseHeaders);

    /**
     * Operation getRolesCustomCustomRoleIdMembers
     *
     * Your GET endpoint
     *
     * @param  string $customRoleId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return string[]
     *
     */
    public function getRolesCustomCustomRoleIdMembers($customRoleId, &$responseCode, array &$responseHeaders);

    /**
     * Operation postRolesCustom
     *
     * @param  OpenAPI\Server\Model\Role $role   (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Role
     *
     */
    public function postRolesCustom(Role $role = null, &$responseCode, array &$responseHeaders);

    /**
     * Operation putRolesCustomCustomRoleId
     *
     * @param  string $customRoleId   (required)
     * @param  OpenAPI\Server\Model\Role $role   (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Role
     *
     */
    public function putRolesCustomCustomRoleId($customRoleId, Role $role = null, &$responseCode, array &$responseHeaders);
}
