<?php
/**
 * SubsidiariesApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Server
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Contact System API
 *
 * This is the spec for the Constact system API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dirk@arends.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use OpenAPI\Server\Model\ApiResponse;
use OpenAPI\Server\Model\Subsidiary;

/**
 * SubsidiariesApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  OpenAPI\Server\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface SubsidiariesApiInterface
{

    /**
     * Sets authentication method contact_auth
     *
     * @param string $value Value of the contact_auth authentication method.
     *
     * @return void
     */
    public function setcontact_auth($value);

    /**
     * Operation deleteSubsidiariesSubsidiaryId
     *
     * @param  string $subsidiaryId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\ApiResponse
     *
     */
    public function deleteSubsidiariesSubsidiaryId($subsidiaryId, &$responseCode, array &$responseHeaders);

    /**
     * Operation deleteSubsidiariesSubsidiaryIdLocal
     *
     * @param  string $subsidiaryId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\ApiResponse
     *
     */
    public function deleteSubsidiariesSubsidiaryIdLocal($subsidiaryId, &$responseCode, array &$responseHeaders);

    /**
     * Operation getSubsidiaries
     *
     * Your GET endpoint
     *
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Subsidiary[]
     *
     */
    public function getSubsidiaries(&$responseCode, array &$responseHeaders);

    /**
     * Operation getSubsidiariesSubsidiaryId
     *
     * Your GET endpoint
     *
     * @param  string $subsidiaryId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Subsidiary
     *
     */
    public function getSubsidiariesSubsidiaryId($subsidiaryId, &$responseCode, array &$responseHeaders);

    /**
     * Operation getSubsidiariesSubsidiaryIdMembers
     *
     * Your GET endpoint
     *
     * @param  string $subsidiaryId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return string[]
     *
     */
    public function getSubsidiariesSubsidiaryIdMembers($subsidiaryId, &$responseCode, array &$responseHeaders);

    /**
     * Operation postSubsidiaries
     *
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function postSubsidiaries(&$responseCode, array &$responseHeaders);

    /**
     * Operation putSubsidiariesSubsidiaryId
     *
     * @param  string $subsidiaryId   (required)
     * @param  OpenAPI\Server\Model\Subsidiary $subsidiary   (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Subsidiary
     *
     */
    public function putSubsidiariesSubsidiaryId($subsidiaryId, Subsidiary $subsidiary = null, &$responseCode, array &$responseHeaders);

    /**
     * Operation putSubsidiariesSubsidiaryIdLocal
     *
     * @param  string $subsidiaryId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\ApiResponse
     *
     */
    public function putSubsidiariesSubsidiaryIdLocal($subsidiaryId, &$responseCode, array &$responseHeaders);
}
