<?php
/**
 * MemberData
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Contact System API
 *
 * This is the spec for the Constact system API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dirk@arends.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the MemberData model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class MemberData 
{
        /**
     * @var string|null
     * @SerializedName("id")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $id;

    /**
     * @var string|null
     * @SerializedName("firstname")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $firstname;

    /**
     * @var string|null
     * @SerializedName("lastname")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $lastname;

    /**
     * @var string|null
     * @SerializedName("nickname")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $nickname;

    /**
     * @var OpenAPI\Server\Model\AddressData|null
     * @SerializedName("address")
     * @Assert\Type("OpenAPI\Server\Model\AddressData")
     * @Type("OpenAPI\Server\Model\AddressData")
     */
    protected $address;

    /**
     * @var OpenAPI\Server\Model\SectionData|null
     * @SerializedName("section")
     * @Assert\Type("OpenAPI\Server\Model\SectionData")
     * @Type("OpenAPI\Server\Model\SectionData")
     */
    protected $section;

    /**
     * @var OpenAPI\Server\Model\RoleData|null
     * @SerializedName("role")
     * @Assert\Type("OpenAPI\Server\Model\RoleData")
     * @Type("OpenAPI\Server\Model\RoleData")
     */
    protected $role;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->id = isset($data['id']) ? $data['id'] : null;
        $this->firstname = isset($data['firstname']) ? $data['firstname'] : null;
        $this->lastname = isset($data['lastname']) ? $data['lastname'] : null;
        $this->nickname = isset($data['nickname']) ? $data['nickname'] : null;
        $this->address = isset($data['address']) ? $data['address'] : null;
        $this->section = isset($data['section']) ? $data['section'] : null;
        $this->role = isset($data['role']) ? $data['role'] : null;
    }

    /**
     * Gets id.
     *
     * @return string|null
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param string|null $id
     *
     * @return $this
     */
    public function setId(string $id = null): ?string
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets firstname.
     *
     * @return string|null
     */
    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    /**
     * Sets firstname.
     *
     * @param string|null $firstname
     *
     * @return $this
     */
    public function setFirstname(string $firstname = null): ?string
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Gets lastname.
     *
     * @return string|null
     */
    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    /**
     * Sets lastname.
     *
     * @param string|null $lastname
     *
     * @return $this
     */
    public function setLastname(string $lastname = null): ?string
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * Gets nickname.
     *
     * @return string|null
     */
    public function getNickname(): ?string
    {
        return $this->nickname;
    }

    /**
     * Sets nickname.
     *
     * @param string|null $nickname
     *
     * @return $this
     */
    public function setNickname(string $nickname = null): ?string
    {
        $this->nickname = $nickname;

        return $this;
    }

    /**
     * Gets address.
     *
     * @return OpenAPI\Server\Model\AddressData|null
     */
    public function getAddress(): ?AddressData
    {
        return $this->address;
    }

    /**
     * Sets address.
     *
     * @param OpenAPI\Server\Model\AddressData|null $address
     *
     * @return $this
     */
    public function setAddress(AddressData $address = null): ?AddressData
    {
        $this->address = $address;

        return $this;
    }

    /**
     * Gets section.
     *
     * @return OpenAPI\Server\Model\SectionData|null
     */
    public function getSection(): ?SectionData
    {
        return $this->section;
    }

    /**
     * Sets section.
     *
     * @param OpenAPI\Server\Model\SectionData|null $section
     *
     * @return $this
     */
    public function setSection(SectionData $section = null): ?SectionData
    {
        $this->section = $section;

        return $this;
    }

    /**
     * Gets role.
     *
     * @return OpenAPI\Server\Model\RoleData|null
     */
    public function getRole(): ?RoleData
    {
        return $this->role;
    }

    /**
     * Sets role.
     *
     * @param OpenAPI\Server\Model\RoleData|null $role
     *
     * @return $this
     */
    public function setRole(RoleData $role = null): ?RoleData
    {
        $this->role = $role;

        return $this;
    }
}


