index:
  path: /
  controller: App\Controller\DefaultController::index
update_token:
  path: /updateToken/{existingToken}/{newToken}
  controller: App\Controller\DefaultController::updateToken
open_api_server:
  resource: "@OpenAPIServerBundle/Resources/config/routing.yml"
  prefix: "/api/v1"
