<?php
/**
 * AuthApiInterface
 * PHP version 7.1.3
 *
 * @category Class
 * @package  OpenAPI\Server
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Contact System API
 *
 * This is the spec for the Constact system API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dirk@arends.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use OpenAPI\Server\Model\JwtErrorData;
use OpenAPI\Server\Model\JwtErrorResponse;
use OpenAPI\Server\Model\JwtInput;

/**
 * AuthApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  OpenAPI\Server\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface AuthApiInterface
{

    /**
     * Operation getJWT
     *
     * Get JWT
     *
     * @param  \OpenAPI\Server\Model\JwtInput $jwtInput   (optional)
     * @param  \int $responseCode     The HTTP response code to return
     * @param  \array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return \OpenAPI\Server\Model\JwtErrorResponse
     */
    public function getJWT(JwtInput $jwtInput = null, &$responseCode, array &$responseHeaders);

    /**
     * Operation refreshJWT
     *
     * Refresh JWT
     *
     * @param  \string $refreshToken  The refresh token (required)
     * @param  \int $responseCode     The HTTP response code to return
     * @param  \array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return \OpenAPI\Server\Model\JwtErrorResponse
     */
    public function refreshJWT(string $refreshToken, &$responseCode, array &$responseHeaders);
}
