index:
    path: /
    controller: App\Controller\DefaultController::index
jwt_token:
    path: /auth/token
jwt_refresh_token:
    path: /auth/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
open_api_server:
    resource: "@OpenAPIServerBundle/Resources/config/routing.yml"
    # prefix: "/api/v1"
