# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/*"
        exclude: "../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}"

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: "../src/Controller"
        tags: ["controller.service_arguments"]

    # app.jwt_token_authenticator:
    #     class: App\Security\Guard\JWTTokenAuthenticator
    #     parent: lexik_jwt_authentication.security.guard.jwt_token_authenticator
    #     autowire: true
    #     autoconfigure: false

    app.api_key_authenticator:
        class: App\Security\Guard\TokenAuthenticator

    contact_system.controller.members:
        class: App\Controller\MembersController
        tags:
            - { name: "open_api_server.api", api: "members" }

    contact_system.controller.roles:
        class: App\Controller\RolesController
        tags:
            - { name: "open_api_server.api", api: "roles" }

    contact_system.controller.sections:
        class: App\Controller\SectionsController
        tags:
            - { name: "open_api_server.api", api: "sections" }

    contact_system.controller.groups:
        class: App\Controller\ScoutGroupsController
        tags:
            - { name: "open_api_server.api", api: "scoutGroups" }

    contact_system.controller.contacts:
        class: App\Controller\ContactsController
        tags:
            - { name: "open_api_server.api", api: "contacts" }
