=begin comment

Contact System API

This is the spec for the Constact system API

The version of the OpenAPI document: 1.0.0
Contact: dirk@arends.com.au
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::ContactsApi');

my $api = WWW::OpenAPIClient::ContactsApi->new();
isa_ok($api, 'WWW::OpenAPIClient::ContactsApi');

#
# create_contact test
#
# uncomment below and update the test
#my $create_contact_contact_input = undef; # replace NULL with a proper value
#my $create_contact_result = $api->create_contact(contact_input => $create_contact_contact_input);

#
# delete_contact_by_id test
#
# uncomment below and update the test
#my $delete_contact_by_id_contact_id = undef; # replace NULL with a proper value
#my $delete_contact_by_id_result = $api->delete_contact_by_id(contact_id => $delete_contact_by_id_contact_id);

#
# get_contact_by_id test
#
# uncomment below and update the test
#my $get_contact_by_id_contact_id = undef; # replace NULL with a proper value
#my $get_contact_by_id_result = $api->get_contact_by_id(contact_id => $get_contact_by_id_contact_id);

#
# get_contacts test
#
# uncomment below and update the test
#my $get_contacts_query = undef; # replace NULL with a proper value
#my $get_contacts_sort = undef; # replace NULL with a proper value
#my $get_contacts_page_size = undef; # replace NULL with a proper value
#my $get_contacts_page = undef; # replace NULL with a proper value
#my $get_contacts_result = $api->get_contacts(query => $get_contacts_query, sort => $get_contacts_sort, page_size => $get_contacts_page_size, page => $get_contacts_page);

#
# get_list_rules_by_contact_id test
#
# uncomment below and update the test
#my $get_list_rules_by_contact_id_contact_id = undef; # replace NULL with a proper value
#my $get_list_rules_by_contact_id_query = undef; # replace NULL with a proper value
#my $get_list_rules_by_contact_id_sort = undef; # replace NULL with a proper value
#my $get_list_rules_by_contact_id_page_size = undef; # replace NULL with a proper value
#my $get_list_rules_by_contact_id_page = undef; # replace NULL with a proper value
#my $get_list_rules_by_contact_id_result = $api->get_list_rules_by_contact_id(contact_id => $get_list_rules_by_contact_id_contact_id, query => $get_list_rules_by_contact_id_query, sort => $get_list_rules_by_contact_id_sort, page_size => $get_list_rules_by_contact_id_page_size, page => $get_list_rules_by_contact_id_page);

#
# patch_contact_by_id test
#
# uncomment below and update the test
#my $patch_contact_by_id_contact_id = undef; # replace NULL with a proper value
#my $patch_contact_by_id_contact_input = undef; # replace NULL with a proper value
#my $patch_contact_by_id_result = $api->patch_contact_by_id(contact_id => $patch_contact_by_id_contact_id, contact_input => $patch_contact_by_id_contact_input);

#
# update_contact_by_id test
#
# uncomment below and update the test
#my $update_contact_by_id_contact_id = undef; # replace NULL with a proper value
#my $update_contact_by_id_contact_input = undef; # replace NULL with a proper value
#my $update_contact_by_id_result = $api->update_contact_by_id(contact_id => $update_contact_by_id_contact_id, contact_input => $update_contact_by_id_contact_input);

