=begin comment

Contact System API

This is the spec for the Constact system API

The version of the OpenAPI document: 1.0.0
Contact: dirk@arends.com.au
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::MembersApi');

my $api = WWW::OpenAPIClient::MembersApi->new();
isa_ok($api, 'WWW::OpenAPIClient::MembersApi');

#
# add_member_role_by_id test
#
{
    my $member_id = undef; # replace NULL with a proper value
    my $role_id = undef; # replace NULL with a proper value
    my $member_role_input = undef; # replace NULL with a proper value
    my $result = $api->add_member_role_by_id(member_id => $member_id, role_id => $role_id, member_role_input => $member_role_input);
}

#
# create_member test
#
{
    my $member_input = undef; # replace NULL with a proper value
    my $result = $api->create_member(member_input => $member_input);
}

#
# delete_member_by_id test
#
{
    my $member_id = undef; # replace NULL with a proper value
    my $result = $api->delete_member_by_id(member_id => $member_id);
}

#
# get_member_by_id test
#
{
    my $member_id = undef; # replace NULL with a proper value
    my $result = $api->get_member_by_id(member_id => $member_id);
}

#
# get_member_contacts_by_id test
#
{
    my $member_id = undef; # replace NULL with a proper value
    my $sort = undef; # replace NULL with a proper value
    my $page_size = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $result = $api->get_member_contacts_by_id(member_id => $member_id, sort => $sort, page_size => $page_size, page => $page);
}

#
# get_member_roles_by_id test
#
{
    my $member_id = undef; # replace NULL with a proper value
    my $sort = undef; # replace NULL with a proper value
    my $page_size = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $result = $api->get_member_roles_by_id(member_id => $member_id, sort => $sort, page_size => $page_size, page => $page);
}

#
# get_members test
#
{
    my $query = undef; # replace NULL with a proper value
    my $sort = undef; # replace NULL with a proper value
    my $page_size = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $result = $api->get_members(query => $query, sort => $sort, page_size => $page_size, page => $page);
}

#
# merge_member test
#
{
    my $member_id = undef; # replace NULL with a proper value
    my $merge_member_id = undef; # replace NULL with a proper value
    my $result = $api->merge_member(member_id => $member_id, merge_member_id => $merge_member_id);
}

#
# patch_member_by_id test
#
{
    my $member_id = undef; # replace NULL with a proper value
    my $member_input = undef; # replace NULL with a proper value
    my $result = $api->patch_member_by_id(member_id => $member_id, member_input => $member_input);
}

#
# remove_member_role_by_id test
#
{
    my $member_id = undef; # replace NULL with a proper value
    my $role_id = undef; # replace NULL with a proper value
    my $result = $api->remove_member_role_by_id(member_id => $member_id, role_id => $role_id);
}

#
# update_member_by_id test
#
{
    my $member_id = undef; # replace NULL with a proper value
    my $member_input = undef; # replace NULL with a proper value
    my $result = $api->update_member_by_id(member_id => $member_id, member_input => $member_input);
}


1;
