=begin comment

Contact System API

This is the spec for the Constact system API

The version of the OpenAPI document: 1.0.0
Contact: dirk@arends.com.au
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::SectionsApi');

my $api = WWW::OpenAPIClient::SectionsApi->new();
isa_ok($api, 'WWW::OpenAPIClient::SectionsApi');

#
# create_section test
#
{
    my $section_input = undef; # replace NULL with a proper value
    my $result = $api->create_section(section_input => $section_input);
}

#
# delete_section_by_id test
#
{
    my $section_id = undef; # replace NULL with a proper value
    my $result = $api->delete_section_by_id(section_id => $section_id);
}

#
# get_members_by_section_id test
#
{
    my $section_id = undef; # replace NULL with a proper value
    my $query = undef; # replace NULL with a proper value
    my $sort = undef; # replace NULL with a proper value
    my $page_size = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $result = $api->get_members_by_section_id(section_id => $section_id, query => $query, sort => $sort, page_size => $page_size, page => $page);
}

#
# get_section_by_id test
#
{
    my $section_id = undef; # replace NULL with a proper value
    my $result = $api->get_section_by_id(section_id => $section_id);
}

#
# get_section_roles_by_id test
#
{
    my $section_id = undef; # replace NULL with a proper value
    my $result = $api->get_section_roles_by_id(section_id => $section_id);
}

#
# get_sections test
#
{
    my $query = undef; # replace NULL with a proper value
    my $sort = undef; # replace NULL with a proper value
    my $page_size = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $result = $api->get_sections(query => $query, sort => $sort, page_size => $page_size, page => $page);
}

#
# update_section_by_id test
#
{
    my $section_id = undef; # replace NULL with a proper value
    my $section_input = undef; # replace NULL with a proper value
    my $result = $api->update_section_by_id(section_id => $section_id, section_input => $section_input);
}


1;
